[phases.setup]
nixPkgs = ["bun", "openssl_3"]
aptPkgs = ["libssl3", "openssl"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bunx prisma generate", "bun run build"]

[start]
cmd = "bun run start"
